### ISSUE TITLE
Filter orgs by name

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#127]
Many incoming orgs don't have an ROR we can use, so we need to filter by their name when updating their records.

When the filter is added, update `cic_orgs.py` to use it for `find_cic_org`

**Comment by ryscher** [comment]
When added, update the docs here
https://github.com/columbia-it/covid-infocommons/blob/main/backend/docs/filtering_apis.md

**Comment by sg3847** [comment]
@ryscher I've updated the Orgs API to filter by name.
