### ISSUE TITLE
Search filter help text

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#142]
add helper text to suggest users remove the directorate filtering if they want to see more results with the same keywords

**Comment by sg3847** [comment]
@ryscher Do you want helper text on all filter fields or just "NSF Directorate/NIH Institute?"? Instead of tooltips on individual fields, how about a tooltip on "**Clear Filter**" instead?

**Comment by ryscher** [comment]
I don't remember what problem this was trying to address. This ticket is old enough that it might have been made before we had "Clear filter".  Closing...
