### ISSUE TITLE
Autocomplete for name search filters

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#171]
When a name is typed in the search filter for Awardee, PI Name, or Program Official, update the autocomplete list to show *all* matching names in the database, not just matches among the 20 that were initially in the facet list. 

This functionality currently exists in the existing CIC site:
<img width="323" alt="Screen Shot 2022-06-22 at 12 56 34 PM" src="https://user-images.githubusercontent.com/605143/175094891-98cb6f21-86f5-4c49-9160-14486696ef4c.png">

**Comment by sg3847** [comment]
@ryscher If we want auto-complete to work for any existing Awardee, PI Name, or Program Official, we will need to get all that information when page loads. I'd mentioned this before, that doing so will impact the page performance as we will be loading much more data on initial load than just 20 X 3 names. 
Also, does this mean that #157 doesn't apply anymore?

**Comment by ryscher** [comment]
We won't be able to load all possible values on page load; there will be too many. Instead, we want to dynamically query and re-load the autocomplete suggestions as the user types. 

I know this is possible. I've done it in raw JS before, just not in React. But there are some suggestions here:
- https://stackoverflow.com/questions/66249791/load-material-ui-autocomplete-suggestions-after-user-input
- https://stackoverflow.com/questions/61970103/reactjs-update-options-by-hitting-api-on-every-input-change-in-autocomplete-co

#157 is related to this, but it's not exactly the same issue.

If this is difficult, I will disable the autocomplete suggestions for these fields until we have a more permanent solution.

**Comment by ryscher** [comment]
Sunaina was able to give us a workaround by increasing the facet size. This is great for the launch, but we will probably need a more scalable solution as the size of the content increases.

I'll move this to "done" until it becomes an issue again.
