### ISSUE TITLE
Allow search page to take a URL parameter to initialize the search

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#177]
We want our search page to be called from other locations (primarily the Drupal CIC site). An external form should be able to set a URL parameter that is sent to the new form, like `/grants?query=pandemic`. The value of the parameter should be treated as if it were typed into the main search field.

**Comment by sg3847** [comment]
@ryscher We also want the query parameter value (if any) to populate the search input box, right?

**Comment by ryscher** [comment]
@sg3847 Yes, please!

**Comment by ryscher** [comment]
@sg3847 Minor update due to my mistake: please change the name of the parameter from `query` to `keywords`. The Drupal site uses `keywords` in a way that is not easy to change.

**Comment by sg3847** [comment]
Done
