### ISSUE TITLE
Upgrade MySQL

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#204]
- [x] dev upgrade
- [x] prod upgrade

**Comment by sg3847** [comment]
CIC-E dev DB has been upgraded to Serverless v2, engine version 8.0.mysql_aurora.3.02.2 supporting MYSQL 8.0.

**Comment by sg3847** [comment]
CIC-E prod DB has been upgraded to Serverless V2, engine version 8.0.mysql_aurora.3.02.2 supporting MYSQL 8.0. Closing this task.
