### ISSUE TITLE
Survey cleanup

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#207]
- [x] change "Your first name" label to "Your first name (plus middle initial, if any)"
- [x] expand width of input fields for first name and last name
- [x] add radio button for PI/Co-PI
- [x] make it clear that the Additional Comments are "for CIC staff"
- [x] validate emails look like an email format
- [x] remove input for "Other institutional email address"
- [x] Allow ORCID input with or without the prefix "https://orcid.org", but ensure the prefix is present when saved to the DB
- [x]  Is it possible to link to the CIC website directly rather than have it in text? If so, it would be great to link to it in the first full paragraph.
- [ ] Similarly, it would be great to link to the NSF awards and the PI database.

**Comment by sg3847** [comment]
@ryscher re the position of PI/Co-PI radio buttons, I think they should go either below award title or below funding agency, and not below award id (as per what we discussed last week). Let me know what you think. Thanks.

**Comment by sg3847** [comment]
@ryscher re Florence's question about sending emails to people when they submit the form, what did we decide? Should I look into how that can be done? If we want to send emails, we will need email content from Lauren/Florence.

**Comment by sg3847** [comment]
Also, if we do send email to people when they submit the form, we can add the information they entered in the form and bcc/cc ourselves which can be our record for original data submitted. Not the most ideal way of keeping track, but we'll have something w.r.t Florence's question about tracking the original data submitted by users.
