### ISSUE TITLE
Survey updates models if they exist

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#208]
When a survey is approved, before creating new records, check whether matching records exist and update as described below.

I'm using the word 'record' to mean the pre-existing record in the CIC database, and 'survey' to mean information that was entered in the survey form.

Person:
- locate a matching Person record based on ORCID, or email if ORCID is not available
- First Name, Last Name: Don't change existing content in the record
- Email: Set the record's email field to the union of the addresses already in the record and the addresses from the survey
- ORCID: Add to the record if it was not present already
- Keywords: Set the record's keywords to the union of the existing keywords in the record and keywords from the survey

Grant:
- locate a matching Grant record based on the combination of Funder and Award ID (both must match)
- Title: Don't change existing content in the record
- Keywords: Set the record's keywords to the union of the existing keywords in the record and keywords from the survey

DOIs:
- for each DOI, check whether it exists in CIC as a Publication or Dataset
- If it exists, leave it alone
- If it does not exist, create a new record

**Comment by sg3847** [comment]
@ryscher 

- Can you include the rules for adding/updating Co-PI when the form is approved? I think we talked about not approving the form if the grant doesn't exist in our system in case the form is submitted by a Co-PI, correct? 
- If the grant exists, and the form is submitted by Co-PI, do we follow the same rules as you described?

**Comment by sg3847** [comment]
@ryscher As part of updating an existing "person", similar to appending the keywords while approving a form, should we append the survey comments and desired collaboration fields as well?
