### ISSUE TITLE
Email confirmation for PI Survey

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#210]
When a user submits the PI survey, send them an email confirmation. The email confirmation should include the text from the confirmation popup, plus a copy of all fields that the user entered into the form.

**Comment by sg3847** [comment]
@ryscher I sent you a test survey confirmation email. It shows up as coming from "ces2295@columbia.edu". This is the new user/account that email team has created for us to use Gmail API. I will be requesting an alias for this email. Hopefully they will give us "covidinfocommons@columbia.edu" as the alias. The "Reply to" address has been set to "covidinfocommons@columbia.edu".
I kind of like the email short and simple, without the data. Normally such emails don't include the survey/form information I think. Let me know what you think.
