### ISSUE TITLE
Initial results message on search page

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#222]
If a user types a search term in the CIC homepage, but it has been a while since the system was used, the search results page will display and say "0 results" until the servers wake up and return results. This is confusing.

Can the results page detect the difference between an actual 0 results and waiting for results to be delivered? Can we make the message less confusing?

**Comment by ryscher** [comment]
Suggested message "Waiting for results..."

**Comment by sg3847** [comment]
Change message to "Searching..." until results are back.
