### ISSUE TITLE
Automate CIC-E deployment

### ISSUE THREAD

**Issue by sg3847** [InfoCommons/cic#236]
We want to combine all the commands used for deploying CIC-E into a single bash script so that we don't have to manually deploy. The script can include:

- Setting Python environment
- Updating Lambda via Zappa
- Building UI code (npm)
- Collecting static files
- Uploading/Updating static files on S3
- Running tests

**Comment by ryscher** [comment]
Sunaina filed a ticket INC2365299 for accessing Jenkins, which will be used for deployment in the future.

**Comment by ryscher** [comment]
The jenkins process proved too difficult. We won't do this.
