### ISSUE TITLE
Document process to update search index

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#253]

**Comment by sg3847** [comment]
I use the Cloud9 environment to connect to the OpenSearch index. Here are the steps I follow:
Login to AWS - https://www.cuit.columbia.edu/aws -> AWS account login
From Services, select Cloud9
Select "connect-to-cice-os-cluster" environment
Click "Open in Cloud9"
Once the environment is open and ready, you can see and access the existing python scripts in the environment. You can create and run new scripts here as well.
For e.g, there is a script called "update_all_pis.py" which updates all the documents in the index with latest PI data. To run this script - 
Activate the existing virtual environment called "venv" using the command $ source venv/bin/activate
Run the script using the command: $ python update_all_pis.py
