### ISSUE TITLE
Allow simple searches within Django Admin

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#254]
When in Django Admin, it can be difficult to find an item that you want to edit. It would be useful for each model to have a very simple search capability, to search by title or primary name.

**Comment by sg3847** [comment]
Search capability has been added in Django admin for the following models/fields:

Person/first name, ID, last name, emails
Grant/title, award ID, PI first name, PI last name
Organization/name, ID, city, state
Publication/DOI, ID, title, grant ID
Dataset/DOI, ID, title, grant ID
Asset/DOI, ID, author ID, grant ID, publication ID
